package sort;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.Comparator;
import java.util.stream.Stream;

import static org.junit.Assert.*;

public class SelectionSortTest {
  @Test
  public void SelectionSort() {
    // Given
    String[] a = {"Z","F","E","B","H"};
    // When
    SelectionSort.sort(a, String::compareTo);
    // Then
    Stream.of(a).reduce((prev, curr) -> {
      assertTrue(prev.compareTo(curr) < 0);
      return curr;
    });
  }
}
