package sort;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.Comparator;
import java.util.stream.Stream;

import static org.junit.Assert.*;

public class SelectionSortTest {

    @Test
    public void SelectionSort() {

        String[] a = {"Z","F","E","B","H"};
        final Comparator<String> com = (s1,s2) -> s1.compareTo(s2);
        SelectionSort.sort(a,com);

        Stream.of(a).reduce((prev, curr) -> {
            assertTrue(com.compare(prev,curr) < 0);
            return curr;
        });
    }
}
